### ISSUE TITLE
Docker Compose syntax incorrect

### ISSUE THREAD

**Issue by jango22** [geerlingguy/shelly-plug-prometheus#11]
I believe that the docker compose syntax is incorrect.
This could be an error from the raspberry pi I am running this on but based on this: https://docs.docker.com/compose/environment-variables/set-environment-variables/ I believe that the environment variables for the docker compose file need to be formatted like one of the following:

1: 
```yaml
---
version: "3"

services:
  shelly-plug:
    container_name: shelly-plug
    image: php:8-apache
    ports:
      - "9924:80"
    environment:
      SHELLY_HOSTNAME: 'my-shelly-plug-host-or-ip'
      SHELLY_HTTP_USERNAME: 'username'
      SHELLY_HTTP_PASSWORD: 'password'
    volumes:
      - './:/var/www/html'
    restart: unless-stopped
```

```yaml
---
version: "3"

services:
  shelly-plug:
    container_name: shelly-plug
    image: php:8-apache
    ports:
      - "9924:80"
    environment:
      - SHELLY_HOSTNAME=my-shelly-plug-host-or-ip
      - SHELLY_HTTP_USERNAME=username
      - SHELLY_HTTP_PASSWORD=password
    volumes:
      - './:/var/www/html'
    restart: unless-stopped
```
